name: Tests
on:
  pull_request:
    branches: [ develop, master, 'release/**' ]
  push:
    branches: [ develop, master, 'release/**' ]

jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Run tests
        run: |
          make test testacc